// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/runner/work/final-admin-ui/final-admin-ui/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
