# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
  release:
    types:
      - published

env:
  namespace: ifinal
  organization: final-apps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub Context
        run: echo "${{ toJson(github) }}"
      - name: 设置环境变量
        uses: final-actions/set-up-env@main
        with:
          docker: true
          docker-registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: 检出存储库
        uses: actions/checkout@v2
      - name: 设置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # 将其更改为所需的Node.js版本
      - name: 安装依赖
        run: npm install
      - name: 构建
        run: npm run build
      - name: 登录Docker镜像源
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 部署 final-sso-app
      - name: final-sso-app
        run: echo "final-sso-app"
      - name: Docker Build And Push
        uses: docker/build-push-action@v5
        env:
          app: final-console-ui
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.organization }}/${{ env.app }}:latest
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.organization }}/${{ env.app }}:${{ env.VERSION }}
      - name: 部署
        uses: final-actions/kuboard-cicd@main
        env:
          app: final-console-ui
        with:
          host: ${{ secrets.KUBOARD_HOST }}
          username: ${{ secrets.KUBOARD_USERNAME }}
          access-key: ${{ secrets.KUBOARD_ACCESS_KEY }}
          cluster: default
          namespace: ${{ env.namespace }}
          app-name: ${{ env.app }}
          image: ${{ secrets.DOCKER_REGISTRY }}/${{ env.organization }}/${{ env.app }}
          version: ${{ env.VERSION }}






